"""Remove Product.type/is_highlighted and introduce ProductPriceFree

Revision ID: 19f9bb88313b
Revises: 162775d9f4f2
Create Date: 2024-09-19 13:45:22.413448

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "19f9bb88313b"
down_revision = "162775d9f4f2"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Stripe data migration already applied on production — skipped here.

    op.alter_column(
        "product_prices",
        "price_currency",
        existing_type=sa.VARCHAR(length=3),
        nullable=True,
    )

    op.alter_column(
        "subscriptions",
        "price_id",
        existing_nullable=True,
        nullable=False,
    )
    op.drop_constraint(
        "subscriptions_price_id_fkey", "subscriptions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("subscriptions_price_id_fkey"),
        "subscriptions",
        "product_prices",
        ["price_id"],
        ["id"],
        ondelete="cascade",
    )

    op.drop_index("idx_organization_id_type", table_name="products")
    op.drop_index("ix_products_is_highlighted", table_name="products")
    op.drop_index("ix_products_type", table_name="products")
    op.drop_column("products", "is_highlighted")
    op.drop_column("products", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "products",
        sa.Column("is_highlighted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.create_index("ix_products_type", "products", ["type"], unique=False)
    op.create_index(
        "ix_products_is_highlighted", "products", ["is_highlighted"], unique=False
    )
    op.create_index(
        "idx_organization_id_type",
        "products",
        ["organization_id", "type"],
        unique=False,
    )

    op.alter_column(
        "subscriptions",
        "price_id",
        nullable=True,
    )
    op.drop_constraint(
        op.f("subscriptions_price_id_fkey"), "subscriptions", type_="foreignkey"
    )
    op.create_foreign_key(
        "subscriptions_price_id_fkey",
        "subscriptions",
        "product_prices",
        ["price_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.alter_column(
        "product_prices",
        "price_currency",
        existing_type=sa.VARCHAR(length=3),
        nullable=False,
    )
    # ### end Alembic commands ###
