"""Add Order.billing_address

Revision ID: 1769a6e618a4
Revises: 6cbeabf73caf
Create Date: 2024-11-26 14:44:03.569035

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports
from polar.kit.address import AddressType

# revision identifiers, used by Alembic.
revision = "1769a6e618a4"
down_revision = "6cbeabf73caf"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "billing_address",
            AddressType(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # Stripe data migration already applied on production — skipped here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "billing_address")
    # ### end Alembic commands ###
