"""Add Order.billing_reason

Revision ID: c4cf133e597c
Revises: 4f890422b67a
Create Date: 2024-10-15 09:19:20.839229

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c4cf133e597c"
down_revision = "4f890422b67a"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("billing_reason", sa.String(), nullable=True))

    op.execute(
        "UPDATE orders SET billing_reason = 'purchase' WHERE subscription_id IS NULL"
    )

    # Stripe data migration already applied on production — skipped here.

    op.alter_column("orders", "billing_reason", nullable=False)

    op.create_index(
        op.f("ix_orders_billing_reason"), "orders", ["billing_reason"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_billing_reason"), table_name="orders")
    op.drop_column("orders", "billing_reason")
    # ### end Alembic commands ###
