"""Remove donation

Revision ID: 6de0c2b1262f
Revises: ebc55e7c3d7d
Create Date: 2024-11-06 14:05:37.475810

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6de0c2b1262f"
down_revision = "ebc55e7c3d7d"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "user_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.execute("UPDATE products SET user_metadata = '{}' WHERE user_metadata IS NULL")
    op.alter_column("products", "user_metadata", nullable=False)

    # Stripe data migration already applied on production — skipped here.

    # Relink held balances donations to orders
    op.execute(
        """
        UPDATE held_balances
        SET order_id = orders.id
        FROM orders
        WHERE held_balances.donation_id = (orders.user_metadata->>'donation_id')::uuid
        """
    )
    # Relink transactions donations to orders
    op.execute(
        """
        UPDATE transactions
        SET order_id = orders.id
        FROM orders
        WHERE transactions.donation_id = (orders.user_metadata->>'donation_id')::uuid
        """
    )
    # Remove "donation.created" event from webhook endpoints
    op.execute(
        """
        UPDATE webhook_endpoints
        SET events = events - 'donation.created'
        WHERE events ? 'donation.created'
        """
    )
    # Remove MaintainerDonationReceived notifications
    op.execute(
        """
        DELETE FROM notifications
        WHERE type = 'MaintainerDonationReceived'
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donations",
        sa.Column("to_organization_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("payment_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("amount", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("amount_received", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("by_user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("by_organization_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "on_behalf_of_organization_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by_user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("charge_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("issue_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "currency", sa.VARCHAR(length=3), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["by_organization_id"],
            ["organizations.id"],
            name="donations_by_organization_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["by_user_id"], ["users.id"], name="donations_by_user_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name="donations_created_by_user_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"], ["issues.id"], name="donations_issue_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["on_behalf_of_organization_id"],
            ["organizations.id"],
            name="donations_on_behalf_of_organization_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["to_organization_id"],
            ["organizations.id"],
            name="donations_to_organization_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="donations_pkey"),
    )
    op.create_index(
        "ix_donations_payment_id", "donations", ["payment_id"], unique=False
    )
    op.create_index(
        "ix_donations_on_behalf_of_organization_id",
        "donations",
        ["on_behalf_of_organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_donations_modified_at", "donations", ["modified_at"], unique=False
    )
    op.create_index("ix_donations_email", "donations", ["email"], unique=False)
    op.create_index(
        "ix_donations_deleted_at", "donations", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_donations_created_at", "donations", ["created_at"], unique=False
    )
    op.create_index("ix_donations_charge_id", "donations", ["charge_id"], unique=False)
    op.create_index(
        "ix_donations_by_user_id", "donations", ["by_user_id"], unique=False
    )
    op.create_index(
        "ix_donations_by_organization_id",
        "donations",
        ["by_organization_id"],
        unique=False,
    )

    op.add_column(
        "transactions",
        sa.Column("donation_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "transactions_donation_id_fkey",
        "transactions",
        "donations",
        ["donation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_transactions_donation_id", "transactions", ["donation_id"], unique=False
    )
    op.drop_column("products", "user_metadata")
    op.add_column(
        "organizations",
        sa.Column(
            "donations_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.execute("UPDATE organizations SET donations_enabled = FALSE")
    op.alter_column("organizations", "donations_enabled", nullable=False)

    op.add_column(
        "held_balances",
        sa.Column("donation_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "held_balances_donation_id_fkey",
        "held_balances",
        "donations",
        ["donation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_held_balances_donation_id", "held_balances", ["donation_id"], unique=False
    )
    # ### end Alembic commands ###
