"""Add Payout.paid_at

Revision ID: d21ac0812338
Revises: 2ffeb5016445
Create Date: 2025-06-19 15:15:28.126423

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d21ac0812338"
down_revision = "2ffeb5016445"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payouts", sa.Column("paid_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    # Stripe data migration already applied on production — skipped here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payouts", "paid_at")
    # ### end Alembic commands ###
