"""remove_seat_based_billing

Revision ID: e4913dfc3774
Revises: gg8899001122
Create Date: 2026-06-06 00:37:54.193438

"""

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "e4913dfc3774"
down_revision = "gg8899001122"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    public_benefits_search_vector_update = PGFunction(
        schema="public",
        signature="benefits_search_vector_update()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        NEW.search_vector := to_tsvector('english', coalesce(NEW.type, '') || ' ' || coalesce(NEW.description, ''));\n        RETURN NEW;\n    END\n    $function$",
    )
    op.drop_entity(public_benefits_search_vector_update)

    op.drop_table("user_notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_deleted_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        op.f("ix_notification_recipients_created_at"),
        table_name="notification_recipients",
    )
    op.drop_index(
        op.f("ix_notification_recipients_deleted_at"),
        table_name="notification_recipients",
    )
    op.drop_index(
        op.f("ix_notification_recipients_expo_push_token"),
        table_name="notification_recipients",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_table("notification_recipients")
    op.drop_index(op.f("ix_customer_seats_created_at"), table_name="customer_seats")
    op.drop_index(op.f("ix_customer_seats_customer_id"), table_name="customer_seats")
    op.drop_index(op.f("ix_customer_seats_deleted_at"), table_name="customer_seats")
    op.drop_index(
        op.f("ix_customer_seats_invitation_token"), table_name="customer_seats"
    )
    op.drop_index(op.f("ix_customer_seats_member_id"), table_name="customer_seats")
    op.drop_index(op.f("ix_customer_seats_order_id"), table_name="customer_seats")
    op.drop_index(
        op.f("ix_customer_seats_subscription_id"), table_name="customer_seats"
    )
    op.drop_table("customer_seats")
    op.drop_column("checkout_links", "require_billing_address")
    op.drop_column("checkouts", "seats")
    op.drop_column("checkouts", "max_seats")
    op.drop_column("checkouts", "min_seats")
    op.drop_column("checkouts", "require_billing_address")
    op.drop_constraint(
        op.f("disputes_dispute_alert_processor_dispute_alert_processor_id_key"),
        "disputes",
        type_="unique",
    )
    op.drop_column("disputes", "dispute_alert_processor_id")
    op.drop_column("disputes", "dispute_alert_processor")
    op.drop_column("orders", "seats")
    op.drop_column("organizations", "avatar_url")
    op.drop_column("product_prices", "seat_tiers")
    op.drop_column("subscription_updates", "seats")
    op.drop_column("subscriptions", "seats")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column("seats", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "subscription_updates",
        sa.Column("seats", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "product_prices",
        sa.Column(
            "seat_tiers",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "organizations",
        sa.Column("avatar_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "orders", sa.Column("seats", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "disputes",
        sa.Column(
            "dispute_alert_processor", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "disputes",
        sa.Column(
            "dispute_alert_processor_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_unique_constraint(
        op.f("disputes_dispute_alert_processor_dispute_alert_processor_id_key"),
        "disputes",
        ["dispute_alert_processor", "dispute_alert_processor_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "checkouts",
        sa.Column(
            "require_billing_address", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "checkouts",
        sa.Column("min_seats", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "checkouts",
        sa.Column("max_seats", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "checkouts",
        sa.Column("seats", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "checkout_links",
        sa.Column(
            "require_billing_address", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.create_table(
        "customer_seats",
        sa.Column("subscription_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("customer_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("invitation_token", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "claimed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "revoked_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "invitation_token_expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("order_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("member_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(length=320), autoincrement=False, nullable=True),
        sa.CheckConstraint(
            "subscription_id IS NOT NULL AND order_id IS NULL OR subscription_id IS NULL AND order_id IS NOT NULL",
            name=op.f("customer_seats_seat_source_check_check"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("customer_seats_customer_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
            name=op.f("customer_seats_member_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("customer_seats_order_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("customer_seats_subscription_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("customer_seats_pkey")),
    )
    op.create_index(
        op.f("ix_customer_seats_subscription_id"),
        "customer_seats",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_seats_order_id"), "customer_seats", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_customer_seats_member_id"),
        "customer_seats",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_seats_invitation_token"),
        "customer_seats",
        ["invitation_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_seats_deleted_at"),
        "customer_seats",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_seats_customer_id"),
        "customer_seats",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_seats_created_at"),
        "customer_seats",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "notification_recipients",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("platform", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("expo_push_token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("notification_recipients_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("notification_recipients_pkey")),
    )
    op.create_index(
        op.f("ix_notification_recipients_expo_push_token"),
        "notification_recipients",
        ["user_id", "expo_push_token", "deleted_at"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        op.f("ix_notification_recipients_deleted_at"),
        "notification_recipients",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_recipients_created_at"),
        "notification_recipients",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("notifications_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("notifications_pkey")),
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_deleted_at"),
        "notifications",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "user_notifications",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "last_read_notification_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("user_notifications_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("user_notifications_pkey")),
    )
    public_benefits_search_vector_update = PGFunction(
        schema="public",
        signature="benefits_search_vector_update()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        NEW.search_vector := to_tsvector('english', coalesce(NEW.type, '') || ' ' || coalesce(NEW.description, ''));\n        RETURN NEW;\n    END\n    $function$",
    )
    op.create_entity(public_benefits_search_vector_update)

    # ### end Alembic commands ###
