"""make_refunds_processor_id_nullable

Revision ID: 60d94b9a0729
Revises: ee5566778899
Create Date: 2026-06-09 19:35:12.451006

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "60d94b9a0729"
down_revision = "ee5566778899"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refunds", "processor_id", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refunds", "processor_id", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
